services:
  productservice:
    build:
      context: ./Products.API/Products.API
      dockerfile: Dockerfile
    restart: always
    container_name: productservice
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__DefaultConnection=Server=productdb,1433;Database=productdb;User Id=sa;Password=Verystrongpassword123;TrustServerCertificate=True;
    depends_on:
      - productdb
    networks:
      - shared-network

  productdb:
    container_name: productdb
    hostname: productdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Verystrongpassword123"
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - shared-network

  angular:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp-angular-container
    ports:
      - "88:80"

volumes:
  mssql_data:

networks:
  shared-network:
    driver: bridge
